keys:
  - &sumelan_sakura age1jfy4xctrua3nttmxdej5537wu3aq24xf2yqpymuvkwe8sds2yqzqx7pcpc
  - &sumelan_minibook age159yqdpkhwlnhd94nu5dvtfc5uhv0crufnvwjp2knpacvsm0du5tscdvaz2
# Note: Be sure to not include a - before subsequent key types under key_groups
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *sumelan_sakura
      - *sumelan_minibook
