keys:
  - &sumelan_sakura age109c3c2ktah7dzv7986kk3xdapweazgs683lcttn3adtj4v2wp96std82l4
  - &sumelan_minibookx age165ucl2th5s9nnqcyzyz3alnc2kcd3qcefew9wv5jnx4dyujgj4fsgkzcfd
# Note: Be sure to not include a - before subsequent key types under key_groups
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *sumelan_sakura
      - *sumelan_minibookx
