# to convert any SSH Ed25519 public key to the age format,
# run `nix-shell -p ssh-to-age --run 'ssh-keyscan example.com | ssh-to-age'`
keys:
  - &sumelan_minibook age159yqdpkhwlnhd94nu5dvtfc5uhv0crufnvwjp2knpacvsm0du5tscdvaz2
  - &sumelan_sakura age1wc74908fkp7zp2y4jdnmy28la0tcas657yr9m0z743y94r4494vqyaw6qc
# Note: Be sure to not include a - before subsequent key types under key_groups
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *sumelan_minibook
      - *sumelan_sakura

