# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dms-plugins = {
    pname = "dms-plugins";
    version = "cf0efeb8311bf59f9f4caec06689100ee5f1aa35";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "dms-plugins";
      rev = "cf0efeb8311bf59f9f4caec06689100ee5f1aa35";
      fetchSubmodules = false;
      sha256 = "sha256-vEoax/uZ3VPe4zw6761dHiPMbYacYlg1hPyORiljWKc=";
    };
    date = "2025-12-14";
  };
}
