# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dms-plugins = {
    pname = "dms-plugins";
    version = "8715ca35b61d7c6275a300fa4992e2b0490f70f7";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "dms-plugins";
      rev = "8715ca35b61d7c6275a300fa4992e2b0490f70f7";
      fetchSubmodules = false;
      sha256 = "sha256-6ScuVcvSaXc35Sf1iwtCy8aM/pFID3+0G4NRMw8aBcM=";
    };
    date = "2025-12-04";
  };
}
