# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dms-plugins = {
    pname = "dms-plugins";
    version = "8fa7c5286171c66a209dd74e9a47d6e72ccfdad6";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "dms-plugins";
      rev = "8fa7c5286171c66a209dd74e9a47d6e72ccfdad6";
      fetchSubmodules = false;
      sha256 = "sha256-0RXRgUXXoX+C0q+drsShjx2rCTdmqFzOCR/1rGB/W2E=";
    };
    date = "2025-12-18";
  };
}
