# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "d7588f6d29b5998733d5a71ec312c7248ba14555";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "d7588f6d29b5998733d5a71ec312c7248ba14555";
      fetchSubmodules = false;
      sha256 = "sha256-9+58QhdM4HVOAfEC224TrPEx1N7F2VLGMxKVLAM4nJw=";
    };
    date = "2025-08-23";
  };
  yazi-starship = {
    pname = "yazi-starship";
    version = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
      fetchSubmodules = false;
      sha256 = "sha256-PYeR6fiWDbUMpJbTFSkM57FzmCbsB4W4IXXe25wLncg=";
    };
    date = "2025-07-08";
  };
}
