[yazi-plugins]
src.git = "https://github.com/yazi-rs/plugins"
fetch.github = "yazi-rs/plugins"

[yazi-starship]
src.git = "https://github.com/Rolv-Apneseth/starship.yazi"
fetch.github = "Rolv-Apneseth/starship.yazi"
