# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "109b13df29f4b7d14fd8e1b38414b205e706c761";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "109b13df29f4b7d14fd8e1b38414b205e706c761";
      fetchSubmodules = false;
      sha256 = "sha256-u8gbZnA8xShsbH06yCZM/aXskMrSHKPcQtIMFp1Cdyo=";
    };
    date = "2025-09-15";
  };
  yazi-starship = {
    pname = "yazi-starship";
    version = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
      fetchSubmodules = false;
      sha256 = "sha256-PYeR6fiWDbUMpJbTFSkM57FzmCbsB4W4IXXe25wLncg=";
    };
    date = "2025-07-08";
  };
}
