[audio]
enable_sounds = true

[backdrop]
enabled = true
blur_intensity = 0.2

[bar]
order = [ "sideBar" ]

    [bar.sideBar]
    background_opacity = 0.5
    capsule_opacity = 0.54999998770654202
    capsule_padding = 10.0
    center = [ "media", "audio_visualizer" ]
    end = [ "recorder", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
    font_family = "Maple Mono NF"
    icon_color = "primary"
    margin_ends = 0
    position = "left"
    radius = 20
    scale = 1.5000000149011612
    start = [ "control-center", "workspaces", "notifications", "privacy" ]
    thickness = 50
    widget_spacing = 20

[brightness]
sync_all_monitors = true

[calendar]
enabled = true

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 64.0
    box_width = 240.0
    cx = 1768.0
    cy = 1144.0
    output = "DSI-1"
    rotation = 0.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        background_opacity = 0.59999999999999998
        color = "hover"
        description = ""
        font_family = "Maple Mono NF"
        opacity = 0.5
        shadow = true
        title = " NixOS"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 80.0
    box_width = 224.0
    cx = 192.0
    cy = 88.0
    output = "DSI-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        center_text = true
        color = "tertiary"
        font_family = "Maple Mono NF"
        format = "{:%H:%M:%S}"

[dock]
active_monitor_only = true
auto_hide = true
background_opacity = 0.34999999217689037

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 400.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 800.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 500.0

[location]
auto_locate = true
[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DSI-1",
    "lockscreen-login-box@HDMI-A-2",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DSI-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 1081.0
    output = "DSI-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DSI-1".settings]
        background_color = "on_tertiary"
        background_opacity = 0.65000000000000002
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1321.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.65000000000000002
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 352.0
    box_width = 704.0
    cx = 1280.0
    cy = 528.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        font_family = "Maple Mono NF"
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 160.0
    box_width = 608.0
    cx = 1280.0
    cy = 1184.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        bands = 32
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 112.0
    box_width = 480.0
    cx = 1280.0
    cy = 1032.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = true
        background_opacity = 0.25
        color = "tertiary"
        font_family = "Montserrat"
        layout = "horizontal"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 224.0
    box_width = 480.0
    cx = 960.0
    cy = 424.0
    output = "DSI-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        color = "tertiary"
        font_family = "Maple Mono NF"
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 160.0
    box_width = 480.0
    cx = 960.0
    cy = 744.0
    output = "DSI-1"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.29999999999999999
        background_padding = 10
        background_radius = 12
        color = "tertiary"
        font_family = "Montserrat"
        hide_when_no_media = false
        layout = "horizontal"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 96.0
    box_width = 496.0
    cx = 960.0
    cy = 936.0
    output = "DSI-1"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        background = false
        bands = 32
        color_1 = "primary"
        color_2 = "secondary"
        show_when_idle = true

[osd]
position = "bottom_center"
position_vertical = "bottom_center"

[plugin_settings."noctalia/mpvpaper"]
picker_placement = "floating"
picker_position = "top_left"
video_directory = "~/Videos/Wallpapers/blueArchive"

[plugins]
enabled = [ "noctalia/notes", "noctalia/mpvpaper", "noctalia/screen_recorder" ]

[shell]
avatar_path = "/home/sumelan/.face"
font_family = "Montserrat"
niri_overview_type_to_launch_enabled = true
polkit_agent = true
settings_show_advanced = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    categories = false
    session_search = false

    [shell.panel]
    clipboard_position = "bottom_center"
    control_center_placement = "floating"
    control_center_position = "top_left"
    launcher_placement = "floating"
    session_placement = "floating"
    session_position = "bottom_center"
    transparency_mode = "glass"
    wallpaper_placement = "floating"
    wallpaper_position = "top_left"

    [shell.screen_corners]
    enabled = true
    size = 40

    [shell.screenshot]
    directory = "/home/sumelan/Pictures/Screenshots"
    pipe_command = "waytator"
    pipe_to_command = true

[theme]
builtin = "Nord"
mode = "dark"
source = "builtin"

    [theme.templates]
    builtin_ids = [ "niri" ]
    community_ids = []

[wallpaper.default]
path = "/home/sumelan/Pictures/Wallpapers/blueArchive/1137852.png"

[wallpaper.last]
path = "/home/sumelan/Pictures/Wallpapers/blueArchive/1137852.png"

[wallpaper.monitors.DSI-1]
path = "/home/sumelan/Pictures/Wallpapers/blueArchive/1137852.png"

[widget.audio_visualizer]
width = 125

[widget.control-center]
font_family = "Montserrat"
glyph = "niri"

[widget.media]
art_size = 25
hide_when_no_media = true
title_scroll = "on_hover"

[widget.notes]
type = "noctalia/notes:notes"

[widget.network]
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.spacer_1]
type = "spacer"

[widget.spacer_2]
type = "spacer"

[widget.tray]
drawer = true

[widget.workspaces]
display = "none"
focused_output_only = true
font_family = "Montserrat"
hide_when_empty = true
labels_only_when_occupied = true
