# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dms-plugins = {
    pname = "dms-plugins";
    version = "141841fc85e01494df6d217bd5a27c65da87256d";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "dms-plugins";
      rev = "141841fc85e01494df6d217bd5a27c65da87256d";
      fetchSubmodules = false;
      sha256 = "sha256-/155wFIotV9xiZzX9XRGs3ANjBcLJwS4kNDDNO6WkF0=";
    };
    date = "2026-02-24";
  };
  helium = {
    pname = "helium";
    version = "0.9.4.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.9.4.1/helium-0.9.4.1-x86_64.AppImage";
      sha256 = "sha256-N5gdWuxOrIudJx/4nYo4/SKSxakpTFvL4zzByv6Cnug=";
    };
  };
  nordic-nvim = {
    pname = "nordic-nvim";
    version = "4ce6bad95fde832f9bd10b991de846047a144628";
    src = fetchFromGitHub {
      owner = "AlexvZyl";
      repo = "nordic.nvim";
      rev = "4ce6bad95fde832f9bd10b991de846047a144628";
      fetchSubmodules = false;
      sha256 = "sha256-kjr4SsRbKfVgNjAFWybkRQ8/QDOPLm7lbysi6Gblpfg=";
    };
    date = "2026-02-07";
  };
}
