# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dms-plugins = {
    pname = "dms-plugins";
    version = "a759ddfccb021ef7e6824685e7a1c3728170977e";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "dms-plugins";
      rev = "a759ddfccb021ef7e6824685e7a1c3728170977e";
      fetchSubmodules = false;
      sha256 = "sha256-s6zQvPoTaJYMA8A/vUEgQhTE/VhQJZwcGw1ET6bOYKg=";
    };
    date = "2026-04-07";
  };
  helium = {
    pname = "helium";
    version = "0.11.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.11.2.1/helium-0.11.2.1-x86_64.AppImage";
      sha256 = "sha256-tGOgJSCGrGfkG2aE0VcGm2GH8ttiBQ602GftlWEHRHA=";
    };
  };
  nordic-nvim = {
    pname = "nordic-nvim";
    version = "9f757428264ef1fcd1703e17702d3a28f307a2f7";
    src = fetchFromGitHub {
      owner = "AlexvZyl";
      repo = "nordic.nvim";
      rev = "9f757428264ef1fcd1703e17702d3a28f307a2f7";
      fetchSubmodules = false;
      sha256 = "sha256-Becp5tPJyjgyVH3BVN6XMKdinZ7JjJ2Czj6c73p6AAk=";
    };
    date = "2026-04-05";
  };
}
