# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dms-plugins = {
    pname = "dms-plugins";
    version = "86c1e03fd8aa106728b46fe3fe4cb085c33fd698";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "dms-plugins";
      rev = "86c1e03fd8aa106728b46fe3fe4cb085c33fd698";
      fetchSubmodules = false;
      sha256 = "sha256-smjvOqmxz46MOm3wasJ/GuHgxZzryIQZ6H6t3IGRx70=";
    };
    date = "2026-01-07";
  };
  helium = {
    pname = "helium";
    version = "0.7.10.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.7.10.1/helium-0.7.10.1-x86_64.AppImage";
      sha256 = "sha256-11xSlHIqmyyVwjjwt5FmLhp72P3m07PppOo7a9DbTcE=";
    };
  };
}
