_: {
  imports = [
    ./desktop
    ./fastfetch
    ./neovim
    ./rmpc
    ./shell
    ./btop.nix
    ./blueman-applet.nix
    ./cava.nix
    ./eza.nix
    ./git.nix
    ./impermanence.nix
    ./jujutsu.nix
    ./kitty.nix
    ./librewolf.nix
    ./mpv.nix
    ./nix.nix
    ./pwvucontrol.nix
    ./ripgrep.nix
    ./starship.nix
    ./swayimg.nix
    ./terminal.nix
    ./thunar.nix
    ./webcord.nix
    ./yazi.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
