# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "7ca66b4103d76038a5d21c9b83766967f5028116";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "7ca66b4103d76038a5d21c9b83766967f5028116";
      fetchSubmodules = false;
      sha256 = "sha256-G4Pqb8ct7om4UfihGr/6GoUn69HbzFVTxlulTeXZyEk=";
    };
    date = "2025-12-24";
  };
}
