# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "19dc890e33b8922eb1a3a165e685436ec4ac0a59";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "19dc890e33b8922eb1a3a165e685436ec4ac0a59";
      fetchSubmodules = false;
      sha256 = "sha256-Hml7n07G6tEOPUPOFN9jf01C5LtZRO8pfERVHKHJQRo=";
    };
    date = "2025-12-04";
  };
}
