# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "1ab21d43c7c6d326c1b9b06610ce7c8686257c43";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "1ab21d43c7c6d326c1b9b06610ce7c8686257c43";
      fetchSubmodules = false;
      sha256 = "sha256-4p+VXUr76kC/dyJZzzkCwNGEUV53YYZ3tYoFpsKboU0=";
    };
    date = "2025-07-20";
  };
  yazi-starship = {
    pname = "yazi-starship";
    version = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
      fetchSubmodules = false;
      sha256 = "sha256-PYeR6fiWDbUMpJbTFSkM57FzmCbsB4W4IXXe25wLncg=";
    };
    date = "2025-07-08";
  };
}
