# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "b8860253fc44e500edeb7a09db648a829084facd";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "b8860253fc44e500edeb7a09db648a829084facd";
      fetchSubmodules = false;
      sha256 = "sha256-29K8PmBoqAMcQhDIfOVnbJt2FU4BR6k23Es9CqyEloo=";
    };
    date = "2025-07-06";
  };
  yazi-starship = {
    pname = "yazi-starship";
    version = "6a0f3f788971b155cbc7cec47f6f11aebbc148c9";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "6a0f3f788971b155cbc7cec47f6f11aebbc148c9";
      fetchSubmodules = false;
      sha256 = "sha256-q1G0Y4JAuAv8+zckImzbRvozVn489qiYVGFQbdCxC98=";
    };
    date = "2025-06-01";
  };
}
