# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "d1c8baab86100afb708694d22b13901b9f9baf00";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "d1c8baab86100afb708694d22b13901b9f9baf00";
      fetchSubmodules = false;
      sha256 = "sha256-52Zn6OSSsuNNAeqqZidjOvfCSB7qPqUeizYq/gO+UbE=";
    };
    date = "2025-09-16";
  };
  yazi-starship = {
    pname = "yazi-starship";
    version = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
      fetchSubmodules = false;
      sha256 = "sha256-PYeR6fiWDbUMpJbTFSkM57FzmCbsB4W4IXXe25wLncg=";
    };
    date = "2025-07-08";
  };
}
