# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "9a52857eac61ede58d11c06ca813c3fa63fe3609";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "9a52857eac61ede58d11c06ca813c3fa63fe3609";
      fetchSubmodules = false;
      sha256 = "sha256-YM53SsE10wtMqI1JGa4CqZbAgr7h62MZ5skEdAavOVA=";
    };
    date = "2025-10-13";
  };
  yazi-starship = {
    pname = "yazi-starship";
    version = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
      fetchSubmodules = false;
      sha256 = "sha256-PYeR6fiWDbUMpJbTFSkM57FzmCbsB4W4IXXe25wLncg=";
    };
    date = "2025-07-08";
  };
}
