{
  lib,
  config,
  pkgs,
  ...
}: let
  inherit (builtins) toString;
  inherit (lib) mkEnableOption getExe;
  inherit
    (lib.custom.colors)
    gray2
    blue2
    orange_bright
    ;
  inherit (config.xdg.userDirs) pictures;

  # output
  inherit (config.lib.monitors) mainMonitor mainMonitorName;
  mainWidth = toString mainMonitor.mode.width;
  mainHeight = toString mainMonitor.mode.height;
  mainRefresh = toString mainMonitor.mode.refresh;
  mainScale = toString mainMonitor.scale;
  mainRotate =
    if mainMonitor.rotation == 0
    then "normal"
    else toString mainMonitor.rotation;
  mainPositionX = toString mainMonitor.position.x;
  mainPositionY = toString mainMonitor.position.y;
  mainMode = "${mainWidth}x${mainHeight}@${mainRefresh}";
  # cursor
  cursorName = config.home.pointerCursor.name;
  cursorSize = toString config.home.pointerCursor.size;
  # xwayland
  xwayland =
    if config.custom.niri.xwayland.enable
    then ''path "${getExe pkgs.xwayland-satellite}"''
    else "off";
in {
  imports = [
    ./animation.nix
    ./keybind.nix
    ./layout.nix
    ./spawn.nix
    ./window-rule.nix
  ];

  options.custom = {
    niri.xwayland.enable = mkEnableOption "xwayland-satellite";
  };

  config = {
    xdg.configFile."niri/config.kdl".text =
      # kdl
      ''
        input {
            keyboard {
                xkb {
                    layout "us"
                    model ""
                    rules ""
                    variant ""
                }
                repeat-delay 600
                repeat-rate 25
                track-layout "global"
            }
            touchpad {
                tap
                natural-scroll
            }
            tablet { map-to-output "DSI-1"; }
            touch { map-to-output "DSI-1"; }
            focus-follows-mouse
        }
        output "${mainMonitorName}" {
            scale ${mainScale}
            transform "${mainRotate}"
            position x=${mainPositionX} y=${mainPositionY}
            mode "${mainMode}"
        }
        screenshot-path "${pictures}/Screenshots/%Y-%m-%d_%H-%M-%S.png"
        cursor {
            xcursor-theme "${cursorName}"
            xcursor-size ${cursorSize}
        }
        hotkey-overlay {
            skip-at-startup
            hide-not-bound
        }
        overview {
            zoom 0.500000
            backdrop-color "#3B4252"
            workspace-shadow { color "${gray2}90"; }
        }
        recent-windows {
            debounce-ms 750
            open-delay-ms 150
            highlight {
                active-color "${blue2}ff"
                urgent-color "${orange_bright}ff"
                padding 30
                corner-radius 0
            }
            previews {
                max-height 480
                max-scale 0.5
            }
            binds {
                Mod+Tab { next-window; }
                Mod+Shift+Tab { previous-window; }
                Mod+grave { next-window filter="app-id"; }
                Mod+Shift+grave { previous-window filter="app-id"; }
            }
        }
        gestures {
            dnd-edge-view-scroll {
                trigger-width 60
                delay-ms 100
                max-speed 1500
            }
        }
        prefer-no-csd
        xwayland-satellite {
            ${xwayland}
        }
        environment {
            "DMS_SCREENSHOT_EDITOR" "satty"
            "ELECTRON_OZONE_PLATFORM_HINT" "auto"
            "GDK_BACKEND" "wayland"
            "QT_QPA_PLATFORM" "wayland"
            "QT_QPA_PLATFORMTHEME" "qt5ct"
            "QT_QPA_PLATFORMTHEME_QT6" "qt6ct"
            "QT_STYLE_OVERRIDE" "kvantum"
            "QT_WAYLAND_DISABLE_WINDOWDECORATION" "1"
            "XDG_CURRENT_DESKTOP" "niri"
            "XDG_SESSION_TYPE" "wayland"
        }

        include "animation.kdl"
        include "binds.kdl"
        include "layout.kdl"
        include "spawn.kdl"
        include "window-rule.kdl"

        // auto-generated by dms
        include "dms/colors.kdl"
        include "dms/layout.kdl"
        include "dms/alttab.kdl"
        include "dms/binds.kdl"
        include "dms/wpblur.kdl"
      '';
  };
}
