# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "8f1d9711bcd0e48af1fcb4153c16d24da76e732d";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "8f1d9711bcd0e48af1fcb4153c16d24da76e732d";
      fetchSubmodules = false;
      sha256 = "sha256-7vsqHvdNimH/YVWegfAo7DfJ+InDr3a1aNU0f+gjcdw=";
    };
    date = "2025-10-22";
  };
}
