# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "2301ff803a033cd16d16e62697474d6cb9a94711";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "2301ff803a033cd16d16e62697474d6cb9a94711";
      fetchSubmodules = false;
      sha256 = "sha256-+lirIBXv3EvztE/1b3zHnQ9r5N3VWBCUuH3gZR52fE0=";
    };
    date = "2025-11-19";
  };
}
