# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "eaf6920b7439fa7164a1c162a249c3c76dc0acd9";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "eaf6920b7439fa7164a1c162a249c3c76dc0acd9";
      fetchSubmodules = false;
      sha256 = "sha256-B6zhZfp3SEaiviIzosI2aD8fk+hQF0epOTKi1qm8V3E=";
    };
    date = "2025-11-25";
  };
}
