# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  vicinae-extensions = {
    pname = "vicinae-extensions";
    version = "ec7334e9bb636f4771580238bd3569b58dbce879";
    src = fetchFromGitHub {
      owner = "vicinaehq";
      repo = "extensions";
      rev = "ec7334e9bb636f4771580238bd3569b58dbce879";
      fetchSubmodules = false;
      sha256 = "sha256-C2b6upygLE6xUP/cTSKZfVjMXOXOOqpP5Xmgb9r2dhA=";
    };
    date = "2025-11-22";
  };
}
